### ISSUE TITLE
graphite permission issues

### ISSUE THREAD

**Issue by josephDunne** [echocat/puppet-graphite#207]
I am using this module to install graphiet on centos 6 (via vagrant) and I get the following HTTPd error:

```
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107] mod_wsgi (pid=5692): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107] mod_wsgi (pid=5692): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107] Traceback (most recent call last):
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]   File "/opt/graphite/conf/graphite.wsgi", line 16, in <module>
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]     from graphite.logger import log
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]   File "/opt/graphite/webapp/graphite/logger.py", line 75, in <module>
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]     log = GraphiteLogger() # import-shared logger instance
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]   File "/opt/graphite/webapp/graphite/logger.py", line 40, in __init__
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]     self.infoHandler = Rotater(self.infoLogFile,when="midnight",backupCount=1)
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]   File "/usr/lib64/python2.6/logging/handlers.py", line 164, in __init__
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]   File "/usr/lib64/python2.6/logging/handlers.py", line 64, in __init__
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]   File "/usr/lib64/python2.6/logging/__init__.py", line 835, in __init__
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]     StreamHandler.__init__(self, self._open())
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]   File "/usr/lib64/python2.6/logging/__init__.py", line 854, in _open
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107]     stream = open(self.baseFilename, self.mode)
[Thu Aug 13 21:03:06 2015] [error] [client 192.168.1.107] IOError: [Errno 13] Permission denied: '/opt/graphite/storage/log/webapp/info.log'
```

The folder is owned by apache so I dont understand why permission is denied.

**Comment by josephDunne** [comment]
is it because my vhost is wrong?

```
apache::vhost { 'graphite.my.domain':
  require => Class['graphite::install'],
  port    => '80',
  docroot => '/opt/graphite/webapp',
  wsgi_application_group      => '%{GLOBAL}',
  wsgi_daemon_process         => 'graphite',
  wsgi_daemon_process_options => {
    processes          => '5',
    threads            => '5',
    display-name       => '%{GROUP}',
    inactivity-timeout => '120',
  },
  wsgi_import_script          => '/opt/graphite/conf/graphite.wsgi',
  wsgi_import_script_options  => {
    process-group     => 'graphite',
    application-group => '%{GLOBAL}'
  },
  wsgi_process_group          => 'graphite',
  wsgi_script_aliases         => {
    '/' => '/opt/graphite/conf/graphite.wsgi'
  },
  headers => [
    'set Access-Control-Allow-Origin "*"',
    'set Access-Control-Allow-Methods "GET, OPTIONS, POST"',
    'set Access-Control-Allow-Headers "origin, authorization, accept"',
  ],
  directories => [{
    path => '/media/',
    order => 'deny,allow',
    allow => 'from all'}
  ]
}
```

**Comment by dwerder** [comment]
Can you send your complete puppet node config. The part with the graphite module config.

You did also change the order of the example. The vhost part has to be executed before the graphite part.
The permissions should be similar to that:
```
-rw-r--r-- 1 root   root    1477 Apr  8  2014 aggregation-rules.conf.example
-rw-r--r-- 1 root   root     242 Sep 17  2014 blacklist.conf
-rw-r--r-- 1 root   root     274 Apr  8  2014 blacklist.conf.example
-rw-r--r-- 1 root   root    2594 Apr  8  2014 carbon.amqp.conf.example
-rw-r--r-- 1 root   root   16381 Feb 27 18:16 carbon.conf
-rw-r--r-- 1 root   root   15483 Apr  8  2014 carbon.conf.example
-rw-r--r-- 1 root   root    1892 Apr  8  2014 dashboard.conf.example
-rw-r--r-- 1 apache apache   616 Feb 27 18:17 graphite.wsgi
-rw-r--r-- 1 root   root     585 Apr  8  2014 graphite.wsgi.example
-rw-r--r-- 1 root   root     729 Apr  8  2014 graphTemplates.conf.example
-rw-r--r-- 1 root   root     893 Apr  8  2014 relay-rules.conf.example
-rw-r--r-- 1 root   root     558 Apr  8  2014 rewrite-rules.conf.example
-rw-r--r-- 1 root   root     870 Mar 20  2014 storage-aggregation.conf
-rw-r--r-- 1 root   root     827 Apr  8  2014 storage-aggregation.conf.example
-rw-r--r-- 1 root   root     464 Mar 20  2014 storage-schemas.conf
-rw-r--r-- 1 root   root     489 Apr  8  2014 storage-schemas.conf.example
-rw-r--r-- 1 root   root     315 Sep 17  2014 whitelist.conf
-rw-r--r-- 1 root   root     315 Apr  8  2014 whitelist.conf.example
```

**Comment by josephDunne** [comment]
I believe the vhost part is executed first thanks to `require => Class['graphite::install'],` I had to do it this way because of other issues I faced getting the example to work (cannot find /opt/graphite/webapp error).

Here is my deafult.pp:
```
include epel

include '::apache'

file { '/usr/bin/pip-python':
   ensure => 'link',
   target => '/usr/bin/pip',
}

class { 'graphite':
  gr_web_server => 'none',
  gr_carbon_ver => '0.9.13',
  gr_whisper_ver => '0.9.13',
  gr_graphite_ver => '0.9.13',
}
apache::vhost { 'graphite.my.domain':
  require => Class['graphite::install'],
  port    => '80',
  docroot => '/opt/graphite/webapp',
  wsgi_application_group      => '%{GLOBAL}',
  wsgi_daemon_process         => 'graphite',
  wsgi_daemon_process_options => {
    processes          => '5',
    threads            => '5',
    display-name       => '%{GROUP}',
    inactivity-timeout => '120',
  },
  wsgi_import_script          => '/opt/graphite/conf/graphite.wsgi',
  wsgi_import_script_options  => {
     process-group     => 'graphite',
     application-group => '%{GLOBAL}'
   },
  wsgi_process_group          => 'graphite',
  wsgi_script_aliases         => {
    '/' => '/opt/graphite/conf/graphite.wsgi'
  },
  headers => [
    'set Access-Control-Allow-Origin "*"',
    'set Access-Control-Allow-Methods "GET, OPTIONS, POST"',
    'set Access-Control-Allow-Headers "origin, authorization, accept"',
  ],
  directories => [{
    path => '/media/',
    order => 'deny,allow',
    allow => 'from all'}
  ]
}
```

my WSGI permissions look the same:

```
drwxr-xr-x. 2 root   root   4.0K Aug 13 22:56 .
drwxr-xr-x. 8 apache apache 4.0K Aug 13 22:56 ..
-rw-r--r--. 1 root   root   1.8K Aug 13 22:56 aggregation-rules.conf.example
-rw-r--r--. 1 root   root    242 Aug 13 22:56 blacklist.conf
-rw-r--r--. 1 root   root    274 Aug 13 22:56 blacklist.conf.example
-rw-r--r--. 1 root   root   2.6K Aug 13 22:56 carbon.amqp.conf.example
-rw-r--r--. 1 root   root    16K Aug 13 22:56 carbon.conf
-rw-r--r--. 1 root   root    16K Aug 13 22:56 carbon.conf.example
-rw-r--r--. 1 root   root   1.9K Aug 13 22:56 dashboard.conf.example
-rw-r--r--. 1 apache apache  616 Aug 13 22:56 graphite.wsgi
-rwxr-xr-x. 1 root   root    929 Aug 13 22:56 graphite.wsgi.example
-rw-r--r--. 1 root   root    979 Aug 13 22:56 graphTemplates.conf.example
-rw-r--r--. 1 root   root    893 Aug 13 22:56 relay-rules.conf.example
-rw-r--r--. 1 root   root    558 Aug 13 22:56 rewrite-rules.conf.example
-rw-r--r--. 1 root   root    870 Aug 13 22:56 storage-aggregation.conf
-rw-r--r--. 1 root   root    827 Aug 13 22:56 storage-aggregation.conf.example
-rw-r--r--. 1 root   root    231 Aug 13 22:56 storage-schemas.conf
-rw-r--r--. 1 root   root    489 Aug 13 22:56 storage-schemas.conf.example
-rw-r--r--. 1 root   root    315 Aug 13 22:56 whitelist.conf
-rw-r--r--. 1 root   root    315 Aug 13 22:56 whitelist.conf.example
```

**Comment by josephDunne** [comment]
I have the same problem with carbon 0.9.12 etc.
Puppet version 3.8.1

**Comment by josephDunne** [comment]
This got me further:
```
chcon --type httpd_sys_rw_content_t /opt/graphite/storage/log/webapp/
```

but now i get:
```
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107] mod_wsgi (pid=1774): Target WSGI script '/opt/graphite/conf/graphite.wsgi' cannot be loaded as Python module.
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107] mod_wsgi (pid=1774): Exception occurred processing WSGI script '/opt/graphite/conf/graphite.wsgi'.
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107] Traceback (most recent call last):
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/opt/graphite/conf/graphite.wsgi", line 18, in <module>
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     import graphite.metrics.search
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/opt/graphite/webapp/graphite/metrics/search.py", line 6, in <module>
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     from graphite.storage import is_pattern, match_entries
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/opt/graphite/webapp/graphite/storage.py", line 9, in <module>
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     from graphite.remote_storage import RemoteStore
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/opt/graphite/webapp/graphite/remote_storage.py", line 8, in <module>
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     from graphite.util import unpickle
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/opt/graphite/webapp/graphite/util.py", line 82, in <module>
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     defaultUser = User.objects.create_user('default','default@localhost.localdomain',randomPassword)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/usr/lib/python2.6/site-packages/django/contrib/auth/models.py", line 160, in create_user
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     user.save(using=self._db)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 463, in save
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     self.save_base(using=using, force_insert=force_insert, force_update=force_update)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 551, in save_base
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 203, in _insert
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     return insert_query(self.model, objs, fields, **kwargs)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 1593, in insert_query
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     return query.get_compiler(using=using).execute_sql(return_id)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/usr/lib/python2.6/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     cursor.execute(sql, params)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]   File "/usr/lib/python2.6/site-packages/django/db/backends/sqlite3/base.py", line 344, in execute
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107]     return Database.Cursor.execute(self, query, params)
[Tue Aug 18 11:09:04 2015] [error] [client 192.168.1.107] DatabaseError: attempt to write a readonly database
```

**Comment by josephDunne** [comment]
so to fix this I had to:

```bash
chcon --type httpd_sys_rw_content_t /opt/graphite/storage/
```

and 

```bash
chown -R apache:apache /opt/graphite/
```

**Comment by josephDunne** [comment]
Please close this ticket unless you want to see if its a bug in the puppet modules

**Comment by dwerder** [comment]
Ah ok. So it seems to be a problem with permissions within SELinux. And you get no problems with the Graphite User, if you change the ownership of /opt/graphite to apache:apache?

**Comment by josephDunne** [comment]
no issues with graphite.

**Comment by josephDunne** [comment]
do you have a vagrant box which you know this module works on?

**Comment by dwerder** [comment]
I don't use Vagrant.

**Comment by dwerder** [comment]
A quick search shows up with that https://github.com/gddk/vagrant-cent65-64-puppet
Maybe its a help.

**Comment by josephDunne** [comment]
I also had to setsebool -P httpd_can_network_connect on
