### ISSUE TITLE
ImportError: No module named django.conf

### ISSUE THREAD

**Issue by alexjfisher** [echocat/puppet-graphite#352]
Hi

I've only just started trying out this module and have pretty quickly bumped into an error.  I'm using CentOS 7.4 with the simplest of manifests.
```puppet
  include ::graphite
```

The catalog applies fine, (some permissions seem to get fixed up on the second puppet run), but when I try to access the web interface, I get a `500 Internal Server Error`.  The following is logged to `/var/log/httpd/graphite-web/graphite-web-error.log`

```
[Thu Nov 23 14:59:44.979136 2017] [:error] [pid 9226] [remote 172.16.14.57:228] mod_wsgi (pid=9226): Target WSGI script '/opt/graphite/conf/graphite_wsgi.py' cannot be loaded as Python module.
[Thu Nov 23 14:59:44.979214 2017] [:error] [pid 9226] [remote 172.16.14.57:228] mod_wsgi (pid=9226): Exception occurred processing WSGI script '/opt/graphite/conf/graphite_wsgi.py'.
[Thu Nov 23 14:59:44.979274 2017] [:error] [pid 9226] [remote 172.16.14.57:228] Traceback (most recent call last):
[Thu Nov 23 14:59:44.979310 2017] [:error] [pid 9226] [remote 172.16.14.57:228]   File "/opt/graphite/conf/graphite_wsgi.py", line 15, in <module>
[Thu Nov 23 14:59:44.979388 2017] [:error] [pid 9226] [remote 172.16.14.57:228]     from django.conf import settings
[Thu Nov 23 14:59:44.979425 2017] [:error] [pid 9226] [remote 172.16.14.57:228] ImportError: No module named django.conf
[Thu Nov 23 14:59:45.034428 2017] [:error] [pid 9226] [remote 172.16.14.57:228] mod_wsgi (pid=9226): Target WSGI script '/opt/graphite/conf/graphite_wsgi.py' cannot be loaded as Python module.
[Thu Nov 23 14:59:45.034465 2017] [:error] [pid 9226] [remote 172.16.14.57:228] mod_wsgi (pid=9226): Exception occurred processing WSGI script '/opt/graphite/conf/graphite_wsgi.py'.
[Thu Nov 23 14:59:45.034496 2017] [:error] [pid 9226] [remote 172.16.14.57:228] Traceback (most recent call last):
[Thu Nov 23 14:59:45.034520 2017] [:error] [pid 9226] [remote 172.16.14.57:228]   File "/opt/graphite/conf/graphite_wsgi.py", line 15, in <module>
[Thu Nov 23 14:59:45.034552 2017] [:error] [pid 9226] [remote 172.16.14.57:228]     from django.conf import settings
[Thu Nov 23 14:59:45.034575 2017] [:error] [pid 9226] [remote 172.16.14.57:228] ImportError: No module named django.conf
```

Being new to both the module *and* graphite itself, I'm a bit lost.  Any suggestions?

**Comment by alexjfisher** [comment]
I'm pretty sure the issue is not module specific, but because I have a system umask of '027' (not 022).
The installed python packages are only readable by root, not apache :(

I think this needs to be fixed in puppet...
